### ISSUE TITLE
Color issues

### ISSUE THREAD

**Issue by LeahArmstrong** [jonathanchu/atom-one-dark-theme#40] opened 2018-02-08 22:23 UTC
Seems like the `#282C34` color isn't rendering properly. Haven't been able to figure out what might be the cause, but it's rendering as a vibrant blue tone:

![screenshot 2018-02-08 17 20 10](https://user-images.githubusercontent.com/1608205/36001521-7de9405e-0cf4-11e8-8a1b-9f9215b22a44.png)

Here's a shot of the hex colors rendering inline:
![screenshot 2018-02-08 17 25 09](https://user-images.githubusercontent.com/1608205/36001662-0f2227ca-0cf5-11e8-9264-07b1d8cfe296.png)

Not getting any errors in the output either.

Emacs 25.3.1
Atom One Dark 0.4.0
Iterm2 Build 3.1.5

**Comment by baco** [comment] 2018-02-09 00:24
Same issue here, running GNU Emacs 25.2.2 on Gnome-Terminal

**Comment by jhacksworth** [comment] 2018-02-09 04:26
(This is a duplicate of #6)

This theme is designed for full, 24-bit, color. Emacs before version 26 can't do full color in the terminal. So, even if the terminal supports 24-bit color, as iTerm does, Emacs 25.x doesn't take advantage of it and many colors will not look right.

Note that a preview release of Emacs 26 is out and enables full color in the terminal. I'm using this theme with it on iTerm and tmux with no issues. 👍 

But for now, if you're using Emacs 25.x and you want to use this theme in the terminal, you'll need to customize the colors that don't look right. You could try the suggestion here: https://github.com/jonathanchu/atom-one-dark-theme/issues/6#issuecomment-271777253

**Comment by zoeycodes** [comment] 2018-02-09 04:28
Thanks, sorry I didn't see that somehow. Feel free to close this.

**Closed as completed** 2018-02-09 15:04 UTC
